export const GET_ALL = 'GET_ALL'

export const ADD_DEPARTMENT = 'ADD_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'
export const UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT'
export const SET_CURRENT_DEPARTMENT = 'SET_CURRENT_DEPARTMENT'

export const ADD_POSITION = 'ADD_POSITION'
export const DELETE_POSITION = 'DELETE_POSITION'
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION'


export const SET_ALERT = 'SET_ALERT'
export const CLEAR_ALERTS = 'CLEAR_ALERTS'
export const REMOVE_ALERT = 'REMOVE_ALERT'