export const VEHICLE_SALE = 'VEHICLE_SALE';
export const GET_VEHICLE_SALES = 'GET_VEHICLE_SALES';
export const SET_ERRORS = 'SET_ERRORS';
export const REMOVE_ERROR = 'REMOVE_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';