export const GET_VEHICLES = 'GET_VEHICLES'
export const SET_ALERTS = 'SET_ALERTS'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const CURRENT_VEHICLE = 'CURRENT_VEHICLE'
export const PURCHASE_COMPLETE = 'PURCHASE_COMPLETE'

