// Auth Types
export const GET_USER = 'GET_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const AUTH_ERROR = 'AUTH_ERROR'
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_RESET = 'AUTH_RESET'

// Default Types
export const GET_DEFAULTS = 'GET_DEFAULTS'
export const DEFAULT_ERROR = 'DEFAULT_ERROR'
export const DEFAULT_LOADING = 'DEFAULT_LOADING'
export const DEFAULT_RESET = 'DEFAULT_RESET'

// Inventory Types
export const GET_INVENTORY = 'GET_INVENTORY'
export const INVENTORY_ERROR = 'INVENTORY_ERROR'
export const INVENTORY_LOADING = 'INVENTORY_LOADING'
export const INVENTORY_RESET = 'INVENTORY_RESET'
export const CURRENT_VEHICLE = 'CURRENT_VEHICLE'

// eEmployee Types
export const GET_EMPLOYEES = 'GET_EMPLOYEES'
export const EMPLOYEE_ERROR = 'EMPLOYEE_ERROR'
export const EMPLOYEE_LOADING = 'CUSTOMER_LOADING'
export const EMPLOYEE_RESET = 'EMPLOYEE_RESET'
export const FILTER_EMPLOYEES = 'FILTER_EMPLOYEES'
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE'

// Customer Types
export const GET_CUSTOMERS = 'GET_CUSTOMERS'
export const CUSTOMER_ERROR = 'CUSTOMER_ERROR'
export const CUSTOMER_LOADING = 'CUSTOMER_LOADING'
export const CUSTOMER_RESET = 'CUSTOMER_RESET'
export const FILTER_CUSTOMERS = 'FILTER_CUSTOMERS'
export const ADD_CUSTOMER = 'ADD_CUSTOMER'
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'


