export const INVENTORYVEHICLES = [{
  "_id": 1,
  "year": 2018,
  "make": "Oldsmobile",
  "model": "88",
  "vin": "WAUEKAFB3BN183900",
  "miles": 64,
  "price": 21454,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl."
}, {
  "_id": 2,
  "year": 2021,
  "make": "Ford",
  "model": "Crown Victoria",
  "vin": "3N1AB7AP0FL466870",
  "miles": 70,
  "price": 24075,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam."
}, {
  "_id": 3,
  "year": 2017,
  "make": "Isuzu",
  "model": "Oasis",
  "vin": "WBAKF5C59DE446519",
  "miles": 10,
  "price": 21245,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla."
}, {
  "_id": 4,
  "year": 2020,
  "make": "GMC",
  "model": "Safari",
  "vin": "SCFAB223X1K849108",
  "miles": 38,
  "price": 21663,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue."
}, {
  "_id": 5,
  "year": 2019,
  "make": "Ford",
  "model": "Ranger",
  "vin": "1G6DJ577890556152",
  "miles": 18,
  "price": 22993,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum."
}, {
  "_id": 6,
  "year": 2021,
  "make": "Chrysler",
  "model": "Concorde",
  "vin": "1C3CDFBA8DD958154",
  "miles": 62,
  "price": 23969,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros."
}, {
  "_id": 7,
  "year": 2017,
  "make": "Chrysler",
  "model": "New Yorker",
  "vin": "WP0AA2A93DS014348",
  "miles": 56,
  "price": 24549,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci."
}, {
  "_id": 8,
  "year": 2018,
  "make": "MINI",
  "model": "Clubman",
  "vin": "3C3CFFHH4DT239301",
  "miles": 81,
  "price": 21316,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula."
}, {
  "_id": 9,
  "year": 2021,
  "make": "Saturn",
  "model": "Aura",
  "vin": "SCFAD22323K481844",
  "miles": 66,
  "price": 20294,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti."
}, {
  "_id": 10,
  "year": 2017,
  "make": "Pontiac",
  "model": "Bonneville",
  "vin": "WBAGN63545D537803",
  "miles": 71,
  "price": 24452,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt."
}, {
  "_id": 11,
  "year": 2019,
  "make": "Mercedes-Benz",
  "model": "SL-Class",
  "vin": "2B3CL3CGXBH073245",
  "miles": 21,
  "price": 22257,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius."
}, {
  "_id": 12,
  "year": 2019,
  "make": "Mitsubishi",
  "model": "Eclipse",
  "vin": "5J6TF2H53FL758665",
  "miles": 38,
  "price": 22234,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis."
}, {
  "_id": 13,
  "year": 2019,
  "make": "Lincoln",
  "model": "Town Car",
  "vin": "5LMJJ3H58BE324153",
  "miles": 29,
  "price": 20935,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti."
}, {
  "_id": 14,
  "year": 2017,
  "make": "Chevrolet",
  "model": "Prizm",
  "vin": "1G6DF5E59D0785239",
  "miles": 3,
  "price": 22731,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus."
}, {
  "_id": 15,
  "year": 2020,
  "make": "Chevrolet",
  "model": "Lumina APV",
  "vin": "SCFPDCGP1EG781943",
  "miles": 27,
  "price": 22608,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum."
}, {
  "_id": 16,
  "year": 2020,
  "make": "Mitsubishi",
  "model": "Raider",
  "vin": "4T1BF3EK3AU187761",
  "miles": 32,
  "price": 22557,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius."
}, {
  "_id": 17,
  "year": 2019,
  "make": "Eagle",
  "model": "Talon",
  "vin": "JM1NC2LFXC0942618",
  "miles": 13,
  "price": 20429,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante."
}, {
  "_id": 18,
  "year": 2017,
  "make": "Infiniti",
  "model": "G",
  "vin": "1FTWX3A59AE403381",
  "miles": 36,
  "price": 24177,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem."
}, {
  "_id": 19,
  "year": 2019,
  "make": "Cadillac",
  "model": "XLR",
  "vin": "WBA3N7C57EK354203",
  "miles": 56,
  "price": 23443,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo."
}, {
  "_id": 20,
  "year": 2020,
  "make": "Lexus",
  "model": "LS",
  "vin": "KNAFX5A84E5497603",
  "miles": 14,
  "price": 24130,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh."
}, {
  "_id": 21,
  "year": 2020,
  "make": "Honda",
  "model": "Passport",
  "vin": "WAUMFAFL7AA816154",
  "miles": 2,
  "price": 22964,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus."
}, {
  "_id": 22,
  "year": 2017,
  "make": "Kia",
  "model": "Sephia",
  "vin": "WA1EY94L19D094297",
  "miles": 71,
  "price": 22149,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem."
}, {
  "_id": 23,
  "year": 2019,
  "make": "Hummer",
  "model": "H3",
  "vin": "WAUEFBFLXDN666323",
  "miles": 78,
  "price": 21280,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti."
}, {
  "_id": 24,
  "year": 2019,
  "make": "Mercury",
  "model": "Topaz",
  "vin": "SCBLF34F06C999662",
  "miles": 21,
  "price": 21175,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros."
}, {
  "_id": 25,
  "year": 2018,
  "make": "Mercedes-Benz",
  "model": "W201",
  "vin": "WAUML44D62N921039",
  "miles": 14,
  "price": 22826,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante."
}, {
  "_id": 26,
  "year": 2021,
  "make": "GMC",
  "model": "1500 Club Coupe",
  "vin": "ZFBCFADH4EZ523867",
  "miles": 93,
  "price": 21018,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis."
}, {
  "_id": 27,
  "year": 2021,
  "make": "Nissan",
  "model": "Frontier",
  "vin": "JTDJTUD39DD852756",
  "miles": 64,
  "price": 20603,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio."
}, {
  "_id": 28,
  "year": 2020,
  "make": "Chevrolet",
  "model": "Suburban 1500",
  "vin": "SCBDC47L07C474395",
  "miles": 41,
  "price": 20708,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Vivamus tortor. Duis mattis egestas metus. Aenean fermentum."
}, {
  "_id": 29,
  "year": 2017,
  "make": "Chevrolet",
  "model": "G-Series G20",
  "vin": "2G4GT5GV6C9658903",
  "miles": 100,
  "price": 20617,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
}, {
  "_id": 30,
  "year": 2018,
  "make": "Honda",
  "model": "Insight",
  "vin": "1G6AB1R32F0672705",
  "miles": 35,
  "price": 22832,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus."
}, {
  "_id": 31,
  "year": 2018,
  "make": "Mitsubishi",
  "model": "GTO",
  "vin": "TRURD38J281743703",
  "miles": 21,
  "price": 20677,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc."
}, {
  "_id": 32,
  "year": 2018,
  "make": "Mitsubishi",
  "model": "Pajero",
  "vin": "WP0AB2A80CU103477",
  "miles": 46,
  "price": 20709,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl."
}, {
  "_id": 33,
  "year": 2021,
  "make": "Plymouth",
  "model": "Laser",
  "vin": "5FRYD4H90GB333004",
  "miles": 67,
  "price": 22217,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo."
}, {
  "_id": 34,
  "year": 2017,
  "make": "Volkswagen",
  "model": "Golf",
  "vin": "5J8TB182X8A684324",
  "miles": 62,
  "price": 23078,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus."
}, {
  "_id": 35,
  "year": 2021,
  "make": "Honda",
  "model": "Prelude",
  "vin": "WA1AGBFEXCD276627",
  "miles": 91,
  "price": 20573,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio."
}, {
  "_id": 36,
  "year": 2017,
  "make": "Ram",
  "model": "1500",
  "vin": "1G4GA5EC3BF179268",
  "miles": 65,
  "price": 22615,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue."
}, {
  "_id": 37,
  "year": 2020,
  "make": "Ford",
  "model": "E350",
  "vin": "4T1BD1EB4EU696256",
  "miles": 24,
  "price": 24877,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio."
}, {
  "_id": 38,
  "year": 2019,
  "make": "Volkswagen",
  "model": "Eurovan",
  "vin": "5J6TF3H33CL533341",
  "miles": 39,
  "price": 22855,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum."
}, {
  "_id": 39,
  "year": 2018,
  "make": "Infiniti",
  "model": "QX",
  "vin": "WBA3B5C51EP320936",
  "miles": 27,
  "price": 21925,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique."
}, {
  "_id": 40,
  "year": 2019,
  "make": "Lincoln",
  "model": "Continental",
  "vin": "19VDE3F78EE245693",
  "miles": 75,
  "price": 23648,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque."
}, {
  "_id": 41,
  "year": 2018,
  "make": "GMC",
  "model": "Safari",
  "vin": "1N6AD0CU9BC796396",
  "miles": 21,
  "price": 22938,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo."
}, {
  "_id": 42,
  "year": 2019,
  "make": "Mercury",
  "model": "Grand Marquis",
  "vin": "JA32X8HW0AU482473",
  "miles": 46,
  "price": 24259,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat."
}, {
  "_id": 43,
  "year": 2020,
  "make": "Geo",
  "model": "Tracker",
  "vin": "WAUGFAFR5DA827997",
  "miles": 46,
  "price": 22963,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis."
}, {
  "_id": 44,
  "year": 2020,
  "make": "Jeep",
  "model": "Liberty",
  "vin": "WBANF33556B208236",
  "miles": 100,
  "price": 20512,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam."
}, {
  "_id": 45,
  "year": 2020,
  "make": "Volkswagen",
  "model": "riolet",
  "vin": "WBADS33422G107229",
  "miles": 57,
  "price": 20323,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor."
}, {
  "_id": 46,
  "year": 2018,
  "make": "Mitsubishi",
  "model": "Starion",
  "vin": "JN8AF5MR9BT078159",
  "miles": 29,
  "price": 23393,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero."
}, {
  "_id": 47,
  "year": 2017,
  "make": "Ford",
  "model": "Fusion",
  "vin": "5J8TB4H36EL392180",
  "miles": 34,
  "price": 21051,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Integer a nibh. In quis justo. Maecenas rhoncus aliquam lacus."
}, {
  "_id": 48,
  "year": 2017,
  "make": "Nissan",
  "model": "Frontier",
  "vin": "SCFFDABM2EG979105",
  "miles": 39,
  "price": 24297,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Sed ante. Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis."
}, {
  "_id": 49,
  "year": 2020,
  "make": "Lincoln",
  "model": "LS",
  "vin": "2G4WE587X61907096",
  "miles": 6,
  "price": 22835,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti."
}, {
  "_id": 50,
  "year": 2020,
  "make": "GMC",
  "model": "Sonoma",
  "vin": "1LNHL9FT4FG231463",
  "miles": 32,
  "price": 22727,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh."
}, {
  "_id": 51,
  "year": 2019,
  "make": "Lexus",
  "model": "SC",
  "vin": "2C3CCAKG8EH235953",
  "miles": 60,
  "price": 23900,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit."
}, {
  "_id": 52,
  "year": 2018,
  "make": "Lotus",
  "model": "Exige",
  "vin": "3VW4A7AT3DM945136",
  "miles": 58,
  "price": 21760,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam."
}, {
  "_id": 53,
  "year": 2020,
  "make": "Mazda",
  "model": "Mazda2",
  "vin": "ZHWGU5BZ6CL274227",
  "miles": 53,
  "price": 24730,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque."
}, {
  "_id": 54,
  "year": 2017,
  "make": "GMC",
  "model": "Canyon",
  "vin": "1G6KD57Y36U127805",
  "miles": 54,
  "price": 22496,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum."
}, {
  "_id": 55,
  "year": 2021,
  "make": "Dodge",
  "model": "Charger",
  "vin": "WBANE53526C602804",
  "miles": 84,
  "price": 22289,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula."
}, {
  "_id": 56,
  "year": 2018,
  "make": "Hyundai",
  "model": "Sonata",
  "vin": "4T1BD1FK4EU072276",
  "miles": 96,
  "price": 23928,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo."
}, {
  "_id": 57,
  "year": 2017,
  "make": "Lincoln",
  "model": "LS",
  "vin": "WAUXL68E44A704272",
  "miles": 54,
  "price": 24925,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti."
}, {
  "_id": 58,
  "year": 2017,
  "make": "GMC",
  "model": "Savana 3500",
  "vin": "WAU4FAFR7BA429609",
  "miles": 12,
  "price": 24514,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat."
}, {
  "_id": 59,
  "year": 2020,
  "make": "Audi",
  "model": "A3",
  "vin": "WAUTFAFH9BN226426",
  "miles": 51,
  "price": 20768,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius."
}, {
  "_id": 60,
  "year": 2017,
  "make": "Scion",
  "model": "tC",
  "vin": "JH4KC1F78EC006403",
  "miles": 56,
  "price": 24983,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam."
}, {
  "_id": 61,
  "year": 2019,
  "make": "Mercury",
  "model": "Sable",
  "vin": "JM1GJ1T62F1113419",
  "miles": 21,
  "price": 22706,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat."
}, {
  "_id": 62,
  "year": 2020,
  "make": "Pontiac",
  "model": "Firebird",
  "vin": "WAUNF78P26A262536",
  "miles": 29,
  "price": 24447,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst."
}, {
  "_id": 63,
  "year": 2021,
  "make": "Ford",
  "model": "Explorer Sport",
  "vin": "1G6D25ED8B0701136",
  "miles": 18,
  "price": 22622,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Aliquam erat volutpat. In congue. Etiam justo."
}, {
  "_id": 64,
  "year": 2019,
  "make": "Land Rover",
  "model": "Range Rover",
  "vin": "WBANW5C53AC062367",
  "miles": 89,
  "price": 20573,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci."
}, {
  "_id": 65,
  "year": 2019,
  "make": "Dodge",
  "model": "Monaco",
  "vin": "3D7TT2CT4AG470959",
  "miles": 49,
  "price": 23995,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst."
}, {
  "_id": 66,
  "year": 2017,
  "make": "Jeep",
  "model": "Wrangler",
  "vin": "2C4RDGCGXFR984074",
  "miles": 93,
  "price": 23760,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis."
}, {
  "_id": 67,
  "year": 2021,
  "make": "Buick",
  "model": "Regal",
  "vin": "KNDJT2A55C7864796",
  "miles": 25,
  "price": 22682,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus."
}, {
  "_id": 68,
  "year": 2018,
  "make": "Chrysler",
  "model": "PT Cruiser",
  "vin": "4T1BD1FK2EU513712",
  "miles": 75,
  "price": 24332,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio."
}, {
  "_id": 69,
  "year": 2019,
  "make": "Nissan",
  "model": "Frontier",
  "vin": "WBAWC7C59AE290791",
  "miles": 67,
  "price": 24401,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius."
}, {
  "_id": 70,
  "year": 2018,
  "make": "Pontiac",
  "model": "Grand Prix",
  "vin": "WAUXL68E74A872228",
  "miles": 53,
  "price": 24570,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem."
}, {
  "_id": 71,
  "year": 2019,
  "make": "Chevrolet",
  "model": "Suburban 1500",
  "vin": "TRURD28N161940369",
  "miles": 36,
  "price": 21550,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum."
}, {
  "_id": 72,
  "year": 2018,
  "make": "Audi",
  "model": "TT",
  "vin": "JM3TB2MA1A0406870",
  "miles": 35,
  "price": 21564,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue."
}, {
  "_id": 73,
  "year": 2017,
  "make": "Toyota",
  "model": "4Runner",
  "vin": "WA1GFCFS9FR319354",
  "miles": 48,
  "price": 21596,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst."
}, {
  "_id": 74,
  "year": 2017,
  "make": "Lexus",
  "model": "LX",
  "vin": "WBAKE5C55CJ373657",
  "miles": 30,
  "price": 21188,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices."
}, {
  "_id": 75,
  "year": 2021,
  "make": "Subaru",
  "model": "Outback",
  "vin": "WAUJT68E22A982798",
  "miles": 87,
  "price": 24760,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus."
}, {
  "_id": 76,
  "year": 2017,
  "make": "BMW",
  "model": "X3",
  "vin": "3D4PH6FV5AT826315",
  "miles": 78,
  "price": 21276,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit."
}, {
  "_id": 77,
  "year": 2021,
  "make": "Nissan",
  "model": "Murano",
  "vin": "ZHWGU6AU6CL340772",
  "miles": 61,
  "price": 21053,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci."
}, {
  "_id": 78,
  "year": 2020,
  "make": "Saturn",
  "model": "L-Series",
  "vin": "1GYFK262X9R606580",
  "miles": 65,
  "price": 23455,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante."
}, {
  "_id": 79,
  "year": 2018,
  "make": "Lincoln",
  "model": "Town Car",
  "vin": "19XFB2F55DE057522",
  "miles": 79,
  "price": 20905,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl."
}, {
  "_id": 80,
  "year": 2020,
  "make": "Acura",
  "model": "TL",
  "vin": "WBAKG7C52DE441591",
  "miles": 37,
  "price": 22665,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum."
}, {
  "_id": 81,
  "year": 2017,
  "make": "Pontiac",
  "model": "Firebird",
  "vin": "WBAAZ33463P178921",
  "miles": 45,
  "price": 22497,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis."
}, {
  "_id": 82,
  "year": 2020,
  "make": "Isuzu",
  "model": "i-Series",
  "vin": "19UUA9E59EA777593",
  "miles": 20,
  "price": 22551,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi."
}, {
  "_id": 83,
  "year": 2020,
  "make": "Audi",
  "model": "S8",
  "vin": "19XFB2F28CE521195",
  "miles": 99,
  "price": 20324,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus."
}, {
  "_id": 84,
  "year": 2021,
  "make": "Chevrolet",
  "model": "Corvette",
  "vin": "JHMZE2H34DS717075",
  "miles": 44,
  "price": 21255,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh."
}, {
  "_id": 85,
  "year": 2021,
  "make": "Ferrari",
  "model": "458 Italia",
  "vin": "1G6DK8EYXB0112349",
  "miles": 38,
  "price": 23682,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem."
}, {
  "_id": 86,
  "year": 2019,
  "make": "Plymouth",
  "model": "Prowler",
  "vin": "3C63D3GL3CG110471",
  "miles": 22,
  "price": 23797,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo."
}, {
  "_id": 87,
  "year": 2021,
  "make": "Jeep",
  "model": "Compass",
  "vin": "1N6AD0CW1EN514570",
  "miles": 50,
  "price": 23084,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst."
}, {
  "_id": 88,
  "year": 2020,
  "make": "Chevrolet",
  "model": "Corvette",
  "vin": "1YVHZ8BHXA5597201",
  "miles": 25,
  "price": 22309,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio."
}, {
  "_id": 89,
  "year": 2021,
  "make": "Audi",
  "model": "V8",
  "vin": "JH4CL95978C200723",
  "miles": 74,
  "price": 22901,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit."
}, {
  "_id": 90,
  "year": 2021,
  "make": "Volvo",
  "model": "S70",
  "vin": "5UXFE8C51AL637074",
  "miles": 35,
  "price": 22656,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim."
}, {
  "_id": 91,
  "year": 2021,
  "make": "Oldsmobile",
  "model": "Bravada",
  "vin": "WAUJT54B33N478616",
  "miles": 25,
  "price": 23908,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui."
}, {
  "_id": 92,
  "year": 2018,
  "make": "Dodge",
  "model": "Grand Caravan",
  "vin": "JN8AE2KP5D9040768",
  "miles": 39,
  "price": 20451,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem."
}, {
  "_id": 93,
  "year": 2019,
  "make": "GMC",
  "model": "Sonoma Club Coupe",
  "vin": "1GYUCCEFXAR856534",
  "miles": 72,
  "price": 24189,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus."
}, {
  "_id": 94,
  "year": 2020,
  "make": "Kia",
  "model": "Sportage",
  "vin": "2C3CDYBTXDH358008",
  "miles": 13,
  "price": 20491,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis."
}, {
  "_id": 95,
  "year": 2018,
  "make": "Lotus",
  "model": "Elise",
  "vin": "5TFBY5F16DX438131",
  "miles": 93,
  "price": 22107,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante."
}, {
  "_id": 96,
  "year": 2017,
  "make": "Mazda",
  "model": "RX-8",
  "vin": "WP0AA2A90DS001718",
  "miles": 68,
  "price": 20909,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl."
}, {
  "_id": 97,
  "year": 2021,
  "make": "Ford",
  "model": "Thunderbird",
  "vin": "WBAVB73587K744330",
  "miles": 2,
  "price": 23622,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy."
}, {
  "_id": 98,
  "year": 2021,
  "make": "Saab",
  "model": "900",
  "vin": "2G4GT5GC5B9220564",
  "miles": 64,
  "price": 24830,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio."
}, {
  "_id": 99,
  "year": 2021,
  "make": "Chevrolet",
  "model": "Monte Carlo",
  "vin": "3D4PH3FG4BT157701",
  "miles": 87,
  "price": 22833,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio."
}, {
  "_id": 100,
  "year": 2017,
  "make": "Toyota",
  "model": "Solara",
  "vin": "1G4GF5G37EF144879",
  "miles": 6,
  "price": 24596,
  "image": "/images/car.jpg",
  "isSold": false,
  "description": "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis."
}]